### ISSUE TITLE
Annotate button is appearing multiple times

### ISSUE THREAD

**Issue by dannthi** [FBarrca/obsidian-handwritten-notes#1]
First of all thanks for this awesome plugin!
I noticed that the button for annotating a PDF is appearing multiple times. The number of buttons in increasing with each second.

**Comment by MelodyDuplaix** [comment]
I've also had this problem for some time.

**Comment by FBarrca** [comment]
Hi, sorry for being absent!

The issue should have been fixed in release [1.2.3](https://github.com/FBarrca/obsidian-handwritten-notes/releases/tag/1.2.3)

Please reopen this issue if you still encounter the issue.

BTW, the plugin is now available in the official community plugin list.
