### ISSUE TITLE
Large amount of annotations lags

### ISSUE THREAD

**Issue by viatii** [FBarrca/obsidian-handwritten-notes#13]
I've been using this plugin for class notes alongside drawboard pdf, and I found that when there are a lot of annotations, obsidian freezes. I haven't noticed any performance issues with large pdfs (100+ pages) but a small 4 page document with writing (>4MB) basically breaks obsidian on any device I try to view it on, which made me think it was the annotation history. I tried to flatten the pdf to see if it made any difference and the lag was completely gone.

I was wondering if there could be a way to disable the annotation history shown on the pdf (I attached an image of what I mean). I'm not entirely sure if this is a plugin issue or an obsidian issue, but I thought I'd mention it.

(sorry if this is a double post, my other account was acting up)
![image](https://github.com/FBarrca/obsidian-handwritten-notes/assets/143142590/a6c15292-0e0b-41f6-b02c-2aa802c2b203)

**Comment by FBarrca** [comment]
Can you please share the file for me to test on?

**Comment by viatii** [comment]
I just shared a private repository with you with the regular pdf and a flattened version. If that doesn't work I can share them here.

**Comment by FBarrca** [comment]
Ah, I see the problem. It seems your annotation app is creating a separate annotation for every stroke. What app are you using?

**Comment by viatii** [comment]
That makes sense. I use Drawboard PDF. I haven't used Xodo or any other app. What app do you personally use? And does it not create separate annotations for each stroke?

**Comment by FBarrca** [comment]
I use Xodo, both on PC and Android(v5.0.22). It works flawlessly.
