### ISSUE TITLE
Is the discord server of this project still active?

### ISSUE THREAD

**Issue by wokawoka** [FBarrca/obsidian-handwritten-notes#14]
I stepped into this project from a [reddit post](https://old.reddit.com/r/ObsidianMD/comments/154p7ou/obsidian_handwritten_notes_community/) where a discord server of the project is listed within the links. That discord invite is invalid atm, and there's no indication of the discord server on the github repo description. 
Is the discord server still active? If so, would it be possible to generate a new valid invite link to it?
Thank you!

**Comment by FBarrca** [comment]
https://discord.gg/ebTcSGwn
Here you go, but it isn't very active
