### ISSUE TITLE
Unable to hand write in ios by using pdf expert

### ISSUE THREAD

**Issue by Dennyyusuf** [FBarrca/obsidian-handwritten-notes#15]
IOS user here,

Thank you very much for the plugin,

But I am still unable to hand write on IOS as I am using pdf expert app, it can open on Pdfexpert but it won't save on obsidian folder.
<img width="654" alt="image" src="https://github.com/FBarrca/obsidian-handwritten-notes/assets/65077044/a759c433-972e-4124-a20a-56a3bf6956ec">

I can edit and hand write successfully by using markup app, 

can you please advice?

Regards,
Denny

**Comment by Dennyyusuf** [comment]
Any help?

**Comment by FBarrca** [comment]
I'll remove it from the README. I don't have an iPad, so I can't test it. The list of compatible apps is made by the community.
