### ISSUE TITLE
Simplify the PDF saving process without having to navigate to the correct folder every time

### ISSUE THREAD

**Issue by tobias0409** [FBarrca/obsidian-handwritten-notes#19]
Hey!
Great plugin! I really appreciate your work.

When I open the PDF on my Android tablet with Samsung Notes and want to save it, I always have to navigate to the correct folder. Is there a way to save PDFs without having to select the folder each time?

Thanks in advance.

**Comment by FBarrca** [comment]
I'm not sure if Samsung Notes is compatible, as the app must not import the note for the plugin to properly work. I know Samsung's Write on PDF works, as I used to use it on my old tablet, maybe try that, or my favorite option, Xodo.
