### ISSUE TITLE
Handwritten Notes on Linux Device

### ISSUE THREAD

**Issue by David-Kyrat** [FBarrca/obsidian-handwritten-notes#23]
Hi I saw that you were searching for user of your plugin on linux.
I am running Fedora-39 and i can say that for what i expected the plugins does work.
I had microsoft edge because i liked their pdf viewer (i know weird right? but they have an option to hide bloat when viewing them) and that is what the plugin opened when i pressed on the pen icon.
When I highlighted text in edge, the changes were reflected in obsidian once the file was saved. 
Text inserting also worked in the same way.

I saw that you wanted to highlight the best editor linux compatible, which is something that i've been doing for a few months now as well. I don't have the time right now to make a full fledged review but i can at least talk about xournal and point you to some alternatives.

#### 1. [Xournal++](https://xournalpp.github.io)
 
What I use.
Probably the most known out there, works decently well, fast and responsive as long as you don't include photos / screenshot of coloured images in +100 pages long documents (I have lots of a pictures of non-cleaned old whiteboard for class in my pfds and it can take a while to save/export). 

But other than that it is still the most stable / best compromise i've really tried to this day.
It is cross platform (I have a surface on windows so, i mainly tested apps that were also usable on windows).

#### 2. [Saber](https://github.com/saber-notes/saber)

Looks promising, ui looks really nice, it has free cloud host storage, its available on ios, android, linux and windows i didn't test it that that much but I will definitely try out later. The only catch is that i didn't find how to insert something other than image (e.g. pdfs)

#### 3. [Scrivano](https://scrivanolabs.github.io)

Would've been the best if not for the lack of file tree view / remember last opened file.

I love the idea of your plugin and i'd like to be able to help you with it. 
(although since I am an "*every-language-but-JS*" dev, i doubt I'll be able to PR)

**Comment by FBarrca** [comment]
Thanks! I'll add them to the README! ❤️

**Comment by mochsner** [comment]
@David-Kyrat to save any others (including me) some trouble, which of the PDF annotator solutions allow you to very quick save as "samefilename.pdf"? Xournal++ doesn't allow you to save as the same PDF name, and saves an XOPP file by default, so it could have a more "native" feel to it imo.
