### ISSUE TITLE
Problematic workflow on iPad with Markup

### ISSUE THREAD

**Issue by deladriere** [FBarrca/obsidian-handwritten-notes#24]
I have a question about using Markup on my iPad. 
When I select the fountain pen icon and choose Markup from the share menu, I can start drawing on the PDF file.
However, I'm having trouble figuring out how to close Markup. 
If I press "Done," it wants to save the PDF, and the only way I've found to exit Markup is to close Obsidian entirely. 
Is there a way to go back to the page where the PDF is embedded without closing Obisidian? Thank you.

**Comment by HWiwoiiii** [comment]
same here

**Comment by RyotaUshio** [comment]
It's very confusing, but actually, you need to tap Done > Delete PDF.

It doesn't delete the original PDF and instead saves the drawings into the original PDF.

I have no idea why Apple designed it like this. Perhaps it may be an unexpected usage for them.

**Comment by deladriere** [comment]
Omg I would never know! Thank you so much !!!

**Comment by FBarrca** [comment]
Thanks! I'll add it to the readme.
