### ISSUE TITLE
Ipad App Support

### ISSUE THREAD

**Issue by jandrefrey** [FBarrca/obsidian-handwritten-notes#25]
Good day. I am trying to use the "Notes Writer" app to edit the pdf's on Ipad.
Unfortunately, the app seems to create a copy of the pdf in its local directory instead of editing the file within the Obsidian directory.
Is this something I'm doing wrong, or is said functionality no longer supported?

**Comment by RyotaUshio** [comment]
On iPad, the built-in _Markup_ works decently.

**Comment by FBarrca** [comment]
I can't guarantee, support for all apps. Please refer to the apps in the README which have been tested by other users.

**Comment by FBarrca** [comment]
Wait, "Notes Writer" is on the list.
I've reopened the issue. @SzymonPawliszyn mentioned in another issue that it works, so I'm not sure. I don't use an iPad myself.

**Comment by RyotaUshio** [comment]
Hi, I've just tried NotesWriter Pro and it worked.

One thing to note: there are two ways to open a PDF file in NotesWriter from Obsidian.

1. "Copy to Notes Writer Pro": This creates a new copy of the original file, and hence it doesn't work.
    <img src="https://github.com/FBarrca/obsidian-handwritten-notes/assets/72342591/51bbe66f-bd76-44df-8305-da909d4bdf50" width=400>

2. In order to modify the original document, we need to tap the Notes Writer Pro icon <img src="https://github.com/FBarrca/obsidian-handwritten-notes/assets/72342591/ae28fcbb-d698-40d3-b162-a3b9d73a9040" width=100>
 at the top of the Share menu.
    <img src="https://github.com/FBarrca/obsidian-handwritten-notes/assets/72342591/1c3c2248-c7b0-4107-a7e9-9e242ba890e3" width=400>

**Comment by FBarrca** [comment]
Great! I'll add it to the README. Thanks for the help!

**Comment by jandrefrey** [comment]
> Hi, I've just tried NotesWriter Pro and it worked.
> 
> One thing to note: there are two ways to open a PDF file in NotesWriter from Obsidian, one of which doesn't work.
> 
>     1. "Copy to Notes Writer Pro": This creates a new copy of the original file, and hence it doesn't work.
>        <img alt="" width="400" src="https://private-user-images.githubusercontent.com/72342591/304063789-51bbe66f-bd76-44df-8305-da909d4bdf50.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU0OTUsIm5iZiI6MTcwNzc0NTE5NSwicGF0aCI6Ii83MjM0MjU5MS8zMDQwNjM3ODktNTFiYmU2NmYtYmQ3Ni00NGRmLTgzMDUtZGE5MDlkNGJkZjUwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzM5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDMyZGM2ZDlkOWY1ZTkxYzk5Y2NmODBlMzM3NjAyNGE0MmJkNDM2ZDRlNWUzZDhkNGI0MGEzZDJmOTYyZTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.npTxlbTYlF9mUvpcFO0C7iJOZ7yNM2MDkimV6FE7iT8">
> 
>     2. In order to modify the original document, we need to tap the Notes Writer Pro icon <img alt="" width="100" src="https://private-user-images.githubusercontent.com/72342591/304066220-ae28fcbb-d698-40d3-b162-a3b9d73a9040.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU0OTUsIm5iZiI6MTcwNzc0NTE5NSwicGF0aCI6Ii83MjM0MjU5MS8zMDQwNjYyMjAtYWUyOGZjYmItZDY5OC00MGQzLWIxNjItYTNiOWQ3M2E5MDQwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzM5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGFjOGYzODI5NzgzODFmY2YyNjMwZWRiY2M3ZDdkYTNmMTIxN2UzNTJhM2E5ZDAwYTUwMzhmYTI0NGUyYzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0uTI9QG_9VhTTb3JRvpuqPULAnpZjIGSk3e9NyEv9jU">
>        at the top of the Share menu.
>        <img alt="" width="400" src="https://private-user-images.githubusercontent.com/72342591/304065553-1c3c2248-c7b0-4107-a7e9-9e242ba890e3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDU0OTUsIm5iZiI6MTcwNzc0NTE5NSwicGF0aCI6Ii83MjM0MjU5MS8zMDQwNjU1NTMtMWMzYzIyNDgtYzdiMC00MTA3LWE3ZTktOWUyNDJiYTg5MGUzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxMzM5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzlkNzg3MDM4NTllZTU4MGFjOGNkNzMyZTBiNWRhNGMwMzg5NjExYjk2NWZiNmJmODZiNjIxZDM0NjJhN2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kd63cDJFzpCpgk36eagqarvhgo_ZZi98NPzAxwbzHlQ">

I have tried both ways with the same result. Even when clicking on the icon, it attempts to copy over the PDF. I believe this is because I am using the free app. I will have to try the pro version to test it again.
