### ISSUE TITLE
Automatically create and embed new file as part of my daily note template?

### ISSUE THREAD

**Issue by robby4769** [FBarrca/obsidian-handwritten-notes#27]
Hi, I really love this plugin - it's gotten me by far the closest to having a real hand-written experience within Obsidian. My use case is iPad Pro. 

Currently, I manually run the command "Handwritten Notes: Create and embed and open from favorite template" every day in my daily note to have a PDF for each day. Is there a way to automate or template this process? 

Thanks!

**Comment by FBarrca** [comment]
Hmm, I'm not really sure… Maybe look into templater or other template plugins, as they might have ways to do so. But I think this is out of the scope of my plugin.
