### ISSUE TITLE
Pdf preview resolution

### ISSUE THREAD

**Issue by PaoEsc** [FBarrca/obsidian-handwritten-notes#29]
I created a rather big pdf page template to use it as a canvas, when I see the file in obsidian with the default reader or embedded in another file the resolution is so low that when zooming in I cannot see the drawings everything is blurry. I don't know exactly where to change these settings.

**Comment by FBarrca** [comment]
The embedding itself is part of the Obsidian core and PDFjs, so there is nothing I can do from my end.
