### ISSUE TITLE
Recommend PDFannotator

### ISSUE THREAD

**Issue by mdelgadoschwar** [FBarrca/obsidian-handwritten-notes#3]
In the documentation you refer to a few pdf annotation programs like Xodo. Unfortunately they all seem to be on a subscription model. 
As a nice alternative check out PDFannotator, for which you pay a reasonable 40USD for lifetime access.

**Comment by FBarrca** [comment]
From what I can see, it's only on Windows, right? I'll add it to the README. Thanks!
