### ISSUE TITLE
Adding PDF templates 

### ISSUE THREAD

**Issue by wemathis** [FBarrca/obsidian-handwritten-notes#32]
Hi I use an iPad. I'm using the Native Markup. I created a template I want to use. However, I don't understand the directions in the plugin options. Under "Templates" the instructions read: "You can use **any** PDF as a template for the notes. Just add it to the templates folder and it will appear here." Then you provide what I assume is file path for the templates folder: 

> .obsidian/plugins/handwritten-notes/templates/

How do I find that folder? 

I'm new to obsidian and markdown. Any help you can offer would be great.

**Comment by YaroKasear** [comment]
Ditto for Android. I can't find any way to get templates in here.

**Comment by thammawat-s** [comment]
For my setup, I sync obsidian vault with my PC, so I can browse using my PC to the template folder and add files there.  and after a sync, I can see my custom templates shown in plug-in setting page on my ipad. 
- my vault\.obsidian.mobile\plugins\handwritten-notes\templates  (for mobile)
- my vault\.obsidian\plugins\handwritten-notes\templates  (for desktop)

**Comment by patrickweindl** [comment]
Loving this plugin as well, as it creates a much more seamless experience on iPadOS (through using MarkUp in my case) than for example Excalidraw.

I've had the same issue of not being able to pass on any templates to the iPad however - subfolders of the plugin folder ./obsidian/plugins/handwritten-notes/templates do not get synced by Obsidian sync.

In case anyone else has that issue, you can use the following workaround (requires a PC/Mac, where the .obsidian folder can be accessed):
- Open file .obsidian/plugins/handwritten-notes/main.js
- Replace all occurences of "this.plugin.manifest.dir + TEMPLATE_DIR" with "TEMPLATE_DIR"
- In line 40 (currently) replace const TEMPLATE_DIR with the folder of your choice (in my case "/Templates/HandwritingTemplates"

This makes the plugin read templates from there and therefore from a folder which actually get's synced to the iPad as well.

**Comment by FBarrca** [comment]
Hello everyone! Just wanted to let you all know that the latest release, [1.3.6](https://github.com/FBarrca/obsidian-handwritten-notes/issues/32) , should have added the custom template folder functionality that you are looking for. You can set a custom folder in the settings.
I myself am a user of Obsidian Sync and I've not had any issues (unless they have changed something on their end recently), I just do as @thammawat-s.
