### ISSUE TITLE
Notes not syncing with xournal++

### ISSUE THREAD

**Issue by GoldenGideon** [FBarrca/obsidian-handwritten-notes#34]
I'm able to create a new note in obsidian and open it in xournal++ normally, but after I mark up the pdf in xournal++ it asks me to save it as a separate file.  If I save it in the xournal++ format then I can't open it in obsidian, and if I manually export it as a pdf then it shows up as a second file in obsidian instead of the one I originally created.  How do I make xournal++ work with the plugin as it should?

**Comment by FBarrca** [comment]
Is this on Linux? I haven't tested that platform, supported apps there are community curated. 
Please let me know if that is the case to update the supported app list accordingly.
