### ISSUE TITLE
Delete handwritten notes when deleting note

### ISSUE THREAD

**Issue by mdelgadoschwar** [FBarrca/obsidian-handwritten-notes#7]
This is just to make sure that I don't pile up on files: 
When I delete a note right now, where the note has embedded one or several handwritten notes, I also need to proceed to delete the handwritten notes (in pdf form) one by one. 

Would it be possible to make sure that if a note is deleted, it's embedded handwritten notes are deleted too? 
This is related to the topic in this forum: https://forum.obsidian.md/t/remove-unused-attachments/4856

There other plugins are already recommended, but I thought that maybe you could directly integrate it within this plugin.

**Comment by FBarrca** [comment]
This is a very opinionated feature for my taste, as I don't think all users would like it to work this way. I would suggest you use any of the solutions on the forums thread.
