### ISSUE TITLE
iOS and iPadOS Experience

### ISSUE THREAD

**Issue by SzymonPawliszyn** [FBarrca/obsidian-handwritten-notes#9]
Hi!
Beside mentioned native markup tool i have _"pleasure"_ of working with those editors:

**PDF Expert** - Great, but for full blown experience you need paid subscription which is pretty expensive.

**PDF Editor** - Also great, but again, subscription is needed although for different options that PDF Expert. (So you can use both of them, for achieving best results, but friction of using 3 apps is annoying).

**Notes Writer** - Overall probably the best of those three, free (you can purchase Pro version super cheap). Only thing it's lacking and it was deal breaker for me is auto shapes (triangles, circles etc.).

**Native Markup** - This is one I use, it's pretty basic but all I need without bells & whistles

**Comment by FBarrca** [comment]
Great! I'll add them to the README.

Thanks

**Comment by Dennyyusuf** [comment]
> Hi! Beside mentioned native markup tool i have _"pleasure"_ of working with those editors:
> 
> **PDF Expert** - Great, but for full blown experience you need paid subscription which is pretty expensive.
> 
> **PDF Editor** - Also great, but again, subscription is needed although for different options that PDF Expert. (So you can use both of them, for achieving best results, but friction of using 3 apps is annoying).
> 
> **Notes Writer** - Overall probably the best of those three, free (you can purchase Pro version super cheap). Only thing it's lacking and it was deal breaker for me is auto shapes (triangles, circles etc.).
> 
> **Native Markup** - This is one I use, it's pretty basic but all I need without bells & whistles

How are you able to work with PDF expert? as whenever I open the hand written notes with PDF expert it does not sync nor save to obsidian.

**Comment by SzymonPawliszyn** [comment]
If I remember correctly (because I don't use it anymore) I have to create pdf through this plugin, then close obsidian and open pdf through pdf expert. However I'm not sure if that was the case. New markup possibilities after last iOS update satisfies all my needs so I abandoned all other software.
